# -*- coding: utf-8 -*-
"""PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifIX8SXZ-u-53X4xpythXdoobsbm2Rvb

# Install & Import
"""

!pip install haversine plotly -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from haversine import haversine
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

"""#  Load & Preview Data"""

df = pd.read_csv('/content/Nassau Candy Distributor.csv')
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nFirst 5 rows:")
df.head()

"""# Clean Data & Create Lead Time"""

# Convert dates
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df['Ship Date']  = pd.to_datetime(df['Ship Date'],  dayfirst=True)

# Target variable
df['Lead Time'] = (df['Ship Date'] - df['Order Date']).dt.days

# Check for nulls
print("Null values:\n", df.isnull().sum())
print("\nLead Time stats:")
print(df['Lead Time'].describe())

"""#  Map Products to Factories"""

factory_map = {
    'Wonka Bar - Nutty Crunch Surprise' : "Lot's O' Nuts",
    'Wonka Bar - Fudge Mallows'         : "Lot's O' Nuts",
    'Wonka Bar -Scrumdiddlyumptious'    : "Lot's O' Nuts",
    'Wonka Bar - Milk Chocolate'        : "Wicked Choccy's",
    'Wonka Bar - Triple Dazzle Caramel' : "Wicked Choccy's",
    'Laffy Taffy'                        : 'Sugar Shack',
    'SweeTARTS'                          : 'Sugar Shack',
    'Nerds'                              : 'Sugar Shack',
    'Fun Dip'                            : 'Sugar Shack',
    'Fizzy Lifting Drinks'               : 'Sugar Shack',
    'Everlasting Gobstopper'             : 'Secret Factory',
    'Lickable Wallpaper'                 : 'Secret Factory',
    'Wonka Gum'                          : 'Secret Factory',
    'Hair Toffee'                        : 'The Other Factory',
    'Kazookles'                          : 'The Other Factory'
}

df['Factory'] = df['Product Name'].map(factory_map)
print(df['Factory'].value_counts())

"""# EDA: Lead Time Charts"""

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Nassau Candy — EDA Overview', fontsize=16, fontweight='bold')

# 1. Avg lead time by factory
df.groupby('Factory')['Lead Time'].mean().sort_values().plot(
    kind='barh', ax=axes[0,0], color='steelblue')
axes[0,0].set_title('Avg Lead Time by Factory (days)')
axes[0,0].set_xlabel('Days')

# 2. Avg lead time by region
df.groupby('Region')['Lead Time'].mean().sort_values().plot(
    kind='barh', ax=axes[0,1], color='coral')
axes[0,1].set_title('Avg Lead Time by Region (days)')

# 3. Lead time by ship mode
df.groupby('Ship Mode')['Lead Time'].mean().sort_values().plot(
    kind='bar', ax=axes[1,0], color='mediumseagreen')
axes[1,0].set_title('Avg Lead Time by Ship Mode')
axes[1,0].set_ylabel('Days')

# 4. Sales by division
df.groupby('Division')['Sales'].sum().plot(
    kind='pie', ax=axes[1,1], autopct='%1.1f%%',
    colors=['#FF6B6B','#4ECDC4','#45B7D1'])
axes[1,1].set_title('Total Sales by Division')
axes[1,1].set_ylabel('')

plt.tight_layout()
plt.savefig('eda_leadtime.png', dpi=150, bbox_inches='tight')
plt.show()

"""# EDA: Profit & Sales Charts"""

fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# Profit by factory
df.groupby('Factory')['Gross Profit'].mean().sort_values().plot(
    kind='barh', ax=axes[0], color='gold')
axes[0].set_title('Avg Gross Profit by Factory')

# Profit by region
df.groupby('Region')['Gross Profit'].mean().sort_values().plot(
    kind='barh', ax=axes[1], color='orchid')
axes[1].set_title('Avg Gross Profit by Region')

# Lead time distribution
axes[2].hist(df['Lead Time'], bins=30, color='tomato', edgecolor='black')
axes[2].set_title('Lead Time Distribution')
axes[2].set_xlabel('Days')
axes[2].set_ylabel('Frequency')

plt.tight_layout()
plt.savefig('eda_profit.png', dpi=150, bbox_inches='tight')
plt.show()

"""# Correlation Heatmap"""

plt.figure(figsize=(8, 5))
sns.heatmap(
    df[['Sales','Units','Gross Profit','Cost','Lead Time']].corr(),
    annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Correlation Heatmap')
plt.savefig('heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

"""# Prepare Features for ML"""

df_model = df.copy()

le = LabelEncoder()
for col in ['Ship Mode', 'Region', 'Factory', 'Division', 'Product Name']:
    df_model[col + '_enc'] = le.fit_transform(df_model[col].astype(str))

features = ['Ship Mode_enc', 'Region_enc', 'Factory_enc',
            'Division_enc', 'Product Name_enc', 'Units', 'Sales', 'Cost']
target = 'Lead Time'

X = df_model[features]
y = df_model[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

print("Train size:", X_train.shape)
print("Test size: ", X_test.shape)

"""# Train & Compare Models"""

models = {
    'Linear Regression' : LinearRegression(),
    'Random Forest'     : RandomForestRegressor(n_estimators=100, random_state=42),
    'Gradient Boosting' : GradientBoostingRegressor(n_estimators=100, random_state=42)
}

results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    results[name] = {
        'RMSE' : round(np.sqrt(mean_squared_error(y_test, preds)), 2),
        'MAE'  : round(mean_absolute_error(y_test, preds), 2),
        'R2'   : round(r2_score(y_test, preds), 4)
    }

results_df = pd.DataFrame(results).T
print(results_df)

"""# Feature Importance"""

best_model = models['Random Forest']

importances = pd.Series(best_model.feature_importances_, index=features)
importances.sort_values().plot(
    kind='barh', figsize=(9, 5), color='teal', edgecolor='black')
plt.title('Feature Importance — Random Forest')
plt.xlabel('Importance Score')
plt.tight_layout()
plt.savefig('feature_importance.png', dpi=150)
plt.show()

"""# Factory Simulation Engine"""

factory_coords = {
    "Lot's O' Nuts"    : (32.881893, -111.768036),
    "Wicked Choccy's"  : (32.076176,  -81.088371),
    "Sugar Shack"       : (48.11914,   -96.18115),
    "Secret Factory"    : (41.446333,  -90.565487),
    "The Other Factory" : (35.1175,    -89.971107)
}

state_coords = {
    'Texas'          : (31.0, -100.0),
    'California'     : (36.7, -119.4),
    'New York'       : (43.0,  -75.0),
    'Florida'        : (27.7,  -81.6),
    'Illinois'       : (40.0,  -89.0),
    'Pennsylvania'   : (41.2,  -77.2),
    'Georgia'        : (32.7,  -83.5),
    'Ohio'           : (40.4,  -82.9),
    'Virginia'       : (37.4,  -78.7),
    'Louisiana'      : (31.1,  -91.8),
    'Washington'     : (47.4, -120.6),
    'Oregon'         : (44.0, -120.5),
    'South Carolina' : (33.8,  -80.9),
    'Kentucky'       : (37.5,  -85.3),
    'Colorado'       : (39.0, -105.5),
    'Arizona'        : (34.0, -111.1),
    'Michigan'       : (44.3,  -85.4),
    'Indiana'        : (40.3,  -86.1),
    'Tennessee'      : (35.8,  -86.4),
    'North Dakota'   : (47.5, -100.5)
}

def simulate_factory(product, state):
    coord = state_coords.get(state, (39.5, -98.4))
    rows = []
    for factory, fc in factory_coords.items():
        dist = haversine(fc, coord)
        rows.append({'Factory': factory, 'Distance_km': round(dist, 1)})
    return pd.DataFrame(rows).sort_values('Distance_km').reset_index(drop=True)

# Test
print(simulate_factory('Wonka Bar - Milk Chocolate', 'California'))

"""# Recommendations Table"""

recs = []
for product in df['Product Name'].unique():
    sub = df[df['Product Name'] == product]
    recs.append({
        'Product'              : product,
        'Current Factory'      : factory_map.get(product, 'Unknown'),
        'Avg Lead Time (days)' : round(sub['Lead Time'].mean(), 1),
        'Avg Gross Profit ($)' : round(sub['Gross Profit'].mean(), 2),
        'Total Orders'         : len(sub)
    })

recs_df = pd.DataFrame(recs).sort_values('Avg Lead Time (days)', ascending=False)
print("=== FACTORY REASSIGNMENT RECOMMENDATIONS ===")
print(recs_df.to_string(index=False))
recs_df.to_csv('recommendations.csv', index=False)

"""# Final Key Performance Indicator Summary

"""

print("=" * 70)
print("   NASSAU CANDY — FINAL KEY PERFORMANCE INDICATOR SUMMARY REPORT")
print("=" * 70)

print(f"\n📦 Total Orders          : {len(df):,}")
print(f"⏱  Avg Lead Time         : {df['Lead Time'].mean():.1f} days")
print(f"🔴 Max Lead Time         : {df['Lead Time'].max()} days")
print(f"🟢 Min Lead Time         : {df['Lead Time'].min()} days")
print(f"💰 Total Revenue         : ${df['Sales'].sum():,.2f}")
print(f"📈 Total Gross Profit    : ${df['Gross Profit'].sum():,.2f}")
print(f"📊 Overall Profit Margin : {df['Gross Profit'].sum()/df['Sales'].sum()*100:.1f}%")

print("\n--- Avg Lead Time by Factory ---")
print(df.groupby('Factory')['Lead Time'].mean().round(1).sort_values())

print("\n--- Profit Margin by Factory ---")
margin = df.groupby('Factory').apply(
    lambda x: round(x['Gross Profit'].sum() / x['Sales'].sum() * 100, 1))
print(margin.sort_values(ascending=False))

print("\n--- Model Performance Summary ---")
print(results_df)
print("\n✅ Best Model: Random Forest")

"""# Streamlit Dashboard"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# 
# st.set_page_config(page_title="Nassau Candy - Factory Optimizer",
#                    layout="wide", page_icon="🍬")
# 
# st.title("🍬 Nassau Candy Distributor — Factory Optimization Dashboard")
# 
# @st.cache_data
# def load_data():
#     df = pd.read_csv('Nassau Candy Distributor.csv')
#     df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
#     df['Ship Date']  = pd.to_datetime(df['Ship Date'],  dayfirst=True)
#     df['Lead Time']  = (df['Ship Date'] - df['Order Date']).dt.days
#     factory_map = {
#         'Wonka Bar - Nutty Crunch Surprise' : "Lot's O' Nuts",
#         'Wonka Bar - Fudge Mallows'         : "Lot's O' Nuts",
#         'Wonka Bar -Scrumdiddlyumptious'    : "Lot's O' Nuts",
#         'Wonka Bar - Milk Chocolate'        : "Wicked Choccy's",
#         'Wonka Bar - Triple Dazzle Caramel' : "Wicked Choccy's",
#         'Laffy Taffy'                        : 'Sugar Shack',
#         'SweeTARTS'                          : 'Sugar Shack',
#         'Nerds'                              : 'Sugar Shack',
#         'Fun Dip'                            : 'Sugar Shack',
#         'Fizzy Lifting Drinks'               : 'Sugar Shack',
#         'Everlasting Gobstopper'             : 'Secret Factory',
#         'Lickable Wallpaper'                 : 'Secret Factory',
#         'Wonka Gum'                          : 'Secret Factory',
#         'Hair Toffee'                        : 'The Other Factory',
#         'Kazookles'                          : 'The Other Factory'
#     }
#     df['Factory'] = df['Product Name'].map(factory_map)
#     return df
# 
# df = load_data()
# 
# # KPI Cards
# st.subheader("📊 Key Metrics")
# col1, col2, col3, col4 = st.columns(4)
# col1.markdown(f"### 📦 Total Orders\n## **{len(df):,}**")
# col2.markdown(f"### ⏱ Avg Lead Time\n## **{int(df['Lead Time'].mean())} days**")
# col3.markdown(f"### 💰 Total Revenue\n## **${df['Sales'].sum():,.0f}**")
# col4.markdown(f"### 📈 Profit Margin\n## **{df['Gross Profit'].sum()/df['Sales'].sum()*100:.1f}%**")
# 
# st.divider()
# 
# tab1, tab2, tab3, tab4 = st.tabs([
#     "🏭 Factory Simulator",
#     "📈 What-If Analysis",
#     "🎯 Recommendations",
#     "⚠️ Risk Panel"
# ])
# 
# with tab1:
#     st.subheader("Factory Optimization Simulator")
#     product = st.selectbox("Select Product", sorted(df['Product Name'].unique()))
#     region  = st.selectbox("Select Region",  sorted(df['Region'].unique()))
#     filtered = df[(df['Product Name'] == product) & (df['Region'] == region)]
#     if len(filtered) > 0:
#         col1, col2 = st.columns(2)
#         with col1:
#             fig = px.bar(
#                 filtered.groupby('Factory')['Lead Time'].mean().reset_index(),
#                 x='Factory', y='Lead Time', color='Factory',
#                 title='Avg Lead Time by Factory')
#             st.plotly_chart(fig, use_container_width=True)
#         with col2:
#             fig2 = px.bar(
#                 filtered.groupby('Factory')['Gross Profit'].mean().reset_index(),
#                 x='Factory', y='Gross Profit', color='Factory',
#                 title='Avg Profit by Factory')
#             st.plotly_chart(fig2, use_container_width=True)
#     else:
#         st.warning("No data for this combination.")
# 
# with tab2:
#     st.subheader("What-If Scenario Analysis")
#     ship_mode = st.selectbox("Ship Mode", sorted(df['Ship Mode'].unique()))
#     st.write("**Optimization Priority (Speed vs Profit):** Use filters above to adjust")
#     scenario = df[df['Ship Mode'] == ship_mode].groupby('Factory').agg(
#         Avg_Lead_Time=('Lead Time',    'mean'),
#         Avg_Profit   =('Gross Profit', 'mean'),
#         Orders       =('Row ID',       'count')
#     ).reset_index()
#     fig = px.scatter(scenario, x='Avg_Lead_Time', y='Avg_Profit',
#                      size='Orders', color='Factory', text='Factory',
#                      title='Lead Time vs Profit by Factory')
#     st.plotly_chart(fig, use_container_width=True)
# 
# with tab3:
#     st.subheader("🎯 Factory Reassignment Recommendations")
#     factory_map_local = {
#         'Wonka Bar - Nutty Crunch Surprise' : "Lot's O' Nuts",
#         'Wonka Bar - Fudge Mallows'         : "Lot's O' Nuts",
#         'Wonka Bar -Scrumdiddlyumptious'    : "Lot's O' Nuts",
#         'Wonka Bar - Milk Chocolate'        : "Wicked Choccy's",
#         'Wonka Bar - Triple Dazzle Caramel' : "Wicked Choccy's",
#         'Laffy Taffy'                        : 'Sugar Shack',
#         'SweeTARTS'                          : 'Sugar Shack',
#         'Nerds'                              : 'Sugar Shack',
#         'Fun Dip'                            : 'Sugar Shack',
#         'Fizzy Lifting Drinks'               : 'Sugar Shack',
#         'Everlasting Gobstopper'             : 'Secret Factory',
#         'Lickable Wallpaper'                 : 'Secret Factory',
#         'Wonka Gum'                          : 'Secret Factory',
#         'Hair Toffee'                        : 'The Other Factory',
#         'Kazookles'                          : 'The Other Factory'
#     }
#     recs = df.groupby('Product Name').agg(
#         Avg_Lead_Time=('Lead Time',    'mean'),
#         Avg_Profit   =('Gross Profit', 'mean'),
#         Total_Orders =('Row ID',       'count')
#     ).reset_index().sort_values('Avg_Lead_Time', ascending=False)
#     recs['Current Factory'] = recs['Product Name'].map(factory_map_local)
#     recs['Avg_Lead_Time']   = recs['Avg_Lead_Time'].round(1)
#     recs['Avg_Profit']      = recs['Avg_Profit'].round(2)
#     st.write(recs[['Product Name','Current Factory',
#                    'Avg_Lead_Time','Avg_Profit',
#                    'Total_Orders']].to_html(index=False),
#              unsafe_allow_html=True)
# 
# with tab4:
#     st.subheader("⚠️ Risk & Impact Panel")
#     high_risk  = df[df['Lead Time'] > df['Lead Time'].quantile(0.75)]
#     low_profit = df[df['Gross Profit'] < 2]
#     col1, col2 = st.columns(2)
#     with col1:
#         st.error(f"🔴 High Lead Time Orders: {len(high_risk):,}")
#         fig = px.histogram(df, x='Lead Time', color='Factory',
#                            title='Lead Time Distribution by Factory')
#         st.plotly_chart(fig, use_container_width=True)
#     with col2:
#         st.warning(f"🟡 Low Profit Orders: {len(low_profit):,}")
#         fig2 = px.box(df, x='Factory', y='Gross Profit', color='Factory',
#                       title='Profit Distribution by Factory')
#         st.plotly_chart(fig2, use_container_width=True)

import subprocess, time, urllib

subprocess.Popen(['streamlit', 'run', 'app.py',
                  '--server.port=8502',
                  '--server.headless=true'])
time.sleep(6)

print("IP:", urllib.request.urlopen(
    'https://ipv4.icanhazip.com').read().decode('utf8').strip())

lt = subprocess.Popen(['lt', '--port', '8502'],
                       stdout=subprocess.PIPE)
time.sleep(3)
print("✅ URL:", lt.stdout.readline().decode('utf8').strip())